### ISSUE TITLE
serverinfo() needs to be for admins only

### ISSUE THREAD

**Issue by crimso4547** [crimso4547/crimsoBOT#20]
This is a small issue that I am creating to test the Discord webhook, but it also needs to be done.

Goal:
- add decorator to serverinfo() to only allow admins to use

**Comment by crimso4547** [comment]
This comment is also to test the webhook.

**Comment by crimso4547** [comment]
This is also a test of the webhook for the crimsoBOT Discord server.

**Comment by williammck** [comment]
Fixed in #19.
